name: vectorize-stack

include:
  - path: ./resources/deploy/compose.yaml
  - path: ./resources/grafana/compose.yaml
  - path: ./resources/caddy/compose.yaml

networks:
  vectorize-network:
    driver: bridge
