[project]
name = "txt2vec-service"
version = "0.1.0"
description = "AWP Projekt für Text Embedding Service"
authors = [
    {name = "ManuelDausmann"},
    {name = "Yannjc"},
    {name = "Dosto1ewski"},
    {name = "BtnCbn"},
    {name = "Yukasama", email = "yukasamaa@gmail.com"},
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic>=2.10.6",
    "pandas>=2.2.3",
    "numpy>=2.2.4",
    "uvicorn[standard]>=0.34.0",
]

[project.scripts]
txt2vec_service = "txt2vec_service.cli:main"

[project.optional-dependencies]
dev = [
    "ruff>=0.11.2",
    "mkdocs>=1.6.1",
    "pytest>=8.3.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/txt2vec_service"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.format]
docstring-code-format = true
quote-style = "preserve"