services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${HOME}/volumes/vectorize/caddy/data:/data
      - ${HOME}/volumes/vectorize/caddy/config:/config
    networks: [vectorize-network]
    restart: unless-stopped
    depends_on:
      - grafana
      - prometheus
      - alloy
      - loki
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 5s
      retries: 3
