global:
  scrape_interval: 10s
scrape_configs:
  - job_name: fastapi
    static_configs:
      # - targets: ["vectorize:8000"] # for production (with docker-compose)
      - targets: ["host.docker.internal:8000"] # for development with localhost
