apiVersion: 1
providers:
  - name: FastAPI
    folder: FastAPI
    type: file
    updateIntervalSeconds: 30
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: true