services:
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - ${HOME}/volumes/sonarqube/data:/opt/sonarqube/data
      - ${HOME}/volumes/sonarqube/logs:/opt/sonarqube/logs:ro
    environment:
      TZ: Europe/Berlin
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4096M
        reservations:
          cpus: "2.0"
          memory: 2048M
