services:
  vectorize:
    image: vectorize:1.0.0-prod # ghcr.io/yukasama/vectorize:latest
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - DATABASE_URL=sqlite+aiosqlite:///./db/app.db
      - UPLOAD_DIR=/app/data/datasets
      - LOG_DIR=/app/log
      - DB_DIR=/app/db
    volumes:
      - ~/volumes/vectorize/data:/app/data
      - ~/volumes/vectorize/log:/app/log
      - ~/volumes/vectorize/db:/app/db
    restart: unless-stopped
    cap_drop: [ALL]
