[app.server]
# host_binding = "0.0.0.0"
# port = 8000
prefix = "/v1"
reload = true
server_header = false

[app.db]
db_logging = true

[app.dataset]
dataset_upload_dir = "data/uploads"
allowed_extensions = ["csv", "json", "xml", "xlsx", "xls"]
max_upload_size = 52428800                                 # 50 MB
max_filename_length = 255
default_delimiter = ";"

[app.model]
model_upload_dir = "data/models"
max_upload_size = 524288000 # 500 MB

[app.logging]
rotation = "1 MB"
log_dir = "log"
log_file = "app.log"
