[app.server]
# host_binding = "0.0.0.0"
# port = 8000
version = "0.1.0"
prefix = "/v1"
reload = true

[app.db]
logging = false
timeout = 30
future = true
max_overflow = 10
pool_size = 5
pool_pre_ping = true
pool_recycle = 300
pool_timeout = 30

[app.dataset]
dataset_upload_dir = "data/datasets"
allowed_extensions = ["csv", "json", "jsonl", "xml", "xlsx", "xls"]
max_upload_size = 53687091200                                       # 50 GB
max_filename_length = 255
default_delimiter = ";"
max_zip_members = 10000

[app.model]
model_upload_dir = "data/models"
max_upload_size = 53687091200    # 50 GB

[app.inference]
device = "cpu"

[app.logging]
rotation = "10 MB"
log_dir = "log"
log_file = "app.log"
