services:
  vectorize:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: vectorize
    volumes:
      - ~/volumes/vectorize/data/datasets:/app/data/datasets
      - ~/volumes/vectorize/data/models:/app/data/models
      - ~/volumes/vectorize/db:/app/db
    env_file: .env
    networks: [vectorize-network]
    restart: unless-stopped
    cap_drop: [ALL]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
