services:
  vectorize:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: vectorize
    volumes:
      - ${HOME}/volumes/vectorize/data/datasets:/app/data/datasets
      - ${HOME}/volumes/vectorize/data/models:/app/data/models
      - ${HOME}/volumes/vectorize/db:/app/db
    environment:
      ENV: production
      DATABASE_URL: sqlite+aiosqlite:///./db/app.db
      UPLOAD_DIR: /app/data/datasets
      MODELS_DIR: /app/data/models
      DB_DIR: /app/db
    networks: [vectorize-network]
    restart: unless-stopped
    cap_drop: [ALL]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
