services:
  vectorize:
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ~/volumes/vectorize/data/datasets:/app/data/datasets
      - ~/volumes/vectorize/data/models:/app/data/models
      - ~/volumes/vectorize/db:/app/db
    restart: unless-stopped
    cap_drop: [ALL]
