services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    cap_drop: [ALL]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/ready"]
      interval: 30s
      timeout: 5s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ${HOME}/volumes/txt2vec/grafana:/var/lib/grafana
      - ${HOME}/volumes/txt2vec/grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - .env
    cap_drop: [ALL]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "9999:9999"
    volumes:
      - ./config/config.alloy:/etc/alloy/config.alloy
    command: ["run", "/etc/alloy/config.alloy"]
    cap_drop: [ALL]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9999/ready"]
      interval: 30s
      timeout: 5s
      retries: 3

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/loki-config.yaml
      - ${HOME}/volumes/txt2vec/loki:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    cap_drop: [ALL]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
