name: Main CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Check for outdated packages
        run: uv pip list --outdated > outdated-packages.txt
        continue-on-error: true

      - name: Run lint with ruff
        uses: astral-sh/ruff-action@v3

      - name: Upload outdated packages reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: outdated-report
          path: outdated-packages.txt
          retention-days: 14

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run tests with pytest
        run: |
          mkdir -p data/uploads
          uv run pytest --html=pytest-report.html --self-contained-html

      - name: Upload test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: pytest-report.html
          retention-days: 14
