name: Main CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv (with caching)
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install project dependencies
        run: uv sync --all-extras --dev --link-mode=copy

      - name: Pack virtual environment
        run: tar -czf venv.tar.gz .venv

      - name: Upload built env
        uses: actions/upload-artifact@v4
        with:
          name: built-venv
          path: venv.tar.gz
          retention-days: 1

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: built-venv

      - run: tar -xzf venv.tar.gz

      - name: Run lint with ruff
        run: .venv/bin/ruff .

  outdated:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: built-venv

      - run: |
          tar -xzf built-venv/venv.tar.gz

      - name: Check for outdated packages
        run: uv pip list --outdated

  tests:
    needs: build
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite+aiosqlite:///./db/app.db

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: built-venv

      - run: tar -xzf venv.tar.gz

      - name: Run tests with pytest
        run: |
          mkdir -p data/uploads
          .venv/bin/pytest \
            --html=pytest-report.html \
            --self-contained-html

      - name: Upload test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: pytest-report.html
          retention-days: 14
