name: Snyk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  security:
    permissions:
      contents: read
      security-events: write

    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Snyk Code test
        run: snyk code test --sarif-file-output=snyk.sarif || true

      - name: Snyk IaC test and report
        run: snyk iac test --report || true

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
